name: Trigger Jenkins Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins Build
      uses: appleboy/jenkins-action@master
      with:
        url: "http://ci.azortis.com"
        user: "example"
        token: ${{ secrets.TOKEN }}
        job: "ZEconomy"
